version: "3"
services:
  nginx:
    shm_size: 64mb
    image: nginx
    depends_on:
    - wordpress
    ports:
      - ${WP_PORT}:80
    volumes:
      - wordpress:/var/www/html
      - ./htdocs/wp-content:/var/www/html/wp-content
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  #
  # WordPress
  #
  wordpress:
    shm_size: 256mb
    image: wordpress:fpm-alpine
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
    volumes:
      - wordpress:/var/www/html
      - ./htdocs/wp-content:/var/www/html/wp-content

  mysql:
    shm_size: 256mb
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    volumes:
      - mysql:/var/lib/mysql

  installer:
    shm_size: 256mb
    image: wordpress:cli
    depends_on:
      - mysql
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./htdocs/wp-content:/var/www/html/wp-content
      - ./:/app
    command: >
      bash /app/sh/wait-for.sh mysql:3306 -t 120 -- bash /app/sh/install.sh ${WP_PORT}


  cli:
    shm_size: 256mb
    image: wordpress:cli
    volumes:
    - wordpress:/var/www/html
    - ./htdocs/wp-content:/var/www/html/wp-content

  composer:
    image: composer
    command: "composer install"
    working_dir: /app
    volumes:
      - wordpress:/var/www/html
      - ./htdocs/wp-content:/var/www/html/wp-content
      - ./:/app

  node:
    image: node:10
    command: "npm install"
    working_dir: /app
    volumes:
    - wordpress:/var/www/html
    - ./htdocs/wp-content:/var/www/html/wp-content
    - ./:/app


volumes:
  wordpress:
    driver: local
  mysql:
    driver: local
